// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: portal/core/proto/rdverb/rdverb.proto

package rdverb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	rdsec "gosuda.org/portal/portal/core/proto/rdsec"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_PACKET_TYPE_RELAY_INFO_REQUEST    PacketType = 0
	PacketType_PACKET_TYPE_RELAY_INFO_RESPONSE   PacketType = 1
	PacketType_PACKET_TYPE_LEASE_UPDATE_REQUEST  PacketType = 2 // Authenticated
	PacketType_PACKET_TYPE_LEASE_UPDATE_RESPONSE PacketType = 3
	PacketType_PACKET_TYPE_LEASE_DELETE_REQUEST  PacketType = 4 // Authenticated
	PacketType_PACKET_TYPE_LEASE_DELETE_RESPONSE PacketType = 5
	PacketType_PACKET_TYPE_CONNECTION_REQUEST    PacketType = 6
	PacketType_PACKET_TYPE_CONNECTION_RESPONSE   PacketType = 7
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "PACKET_TYPE_RELAY_INFO_REQUEST",
		1: "PACKET_TYPE_RELAY_INFO_RESPONSE",
		2: "PACKET_TYPE_LEASE_UPDATE_REQUEST",
		3: "PACKET_TYPE_LEASE_UPDATE_RESPONSE",
		4: "PACKET_TYPE_LEASE_DELETE_REQUEST",
		5: "PACKET_TYPE_LEASE_DELETE_RESPONSE",
		6: "PACKET_TYPE_CONNECTION_REQUEST",
		7: "PACKET_TYPE_CONNECTION_RESPONSE",
	}
	PacketType_value = map[string]int32{
		"PACKET_TYPE_RELAY_INFO_REQUEST":    0,
		"PACKET_TYPE_RELAY_INFO_RESPONSE":   1,
		"PACKET_TYPE_LEASE_UPDATE_REQUEST":  2,
		"PACKET_TYPE_LEASE_UPDATE_RESPONSE": 3,
		"PACKET_TYPE_LEASE_DELETE_REQUEST":  4,
		"PACKET_TYPE_LEASE_DELETE_RESPONSE": 5,
		"PACKET_TYPE_CONNECTION_REQUEST":    6,
		"PACKET_TYPE_CONNECTION_RESPONSE":   7,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_portal_core_proto_rdverb_rdverb_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_portal_core_proto_rdverb_rdverb_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{0}
}

type ResponseCode int32

const (
	ResponseCode_RESPONSE_CODE_UNKNOWN          ResponseCode = 0
	ResponseCode_RESPONSE_CODE_ACCEPTED         ResponseCode = 1
	ResponseCode_RESPONSE_CODE_INVALID_EXPIRES  ResponseCode = 2
	ResponseCode_RESPONSE_CODE_INVALID_IDENTITY ResponseCode = 3
	ResponseCode_RESPONSE_CODE_INVALID_NAME     ResponseCode = 4
	ResponseCode_RESPONSE_CODE_INVALID_ALPN     ResponseCode = 5
	ResponseCode_RESPONSE_CODE_REJECTED         ResponseCode = 6
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "RESPONSE_CODE_UNKNOWN",
		1: "RESPONSE_CODE_ACCEPTED",
		2: "RESPONSE_CODE_INVALID_EXPIRES",
		3: "RESPONSE_CODE_INVALID_IDENTITY",
		4: "RESPONSE_CODE_INVALID_NAME",
		5: "RESPONSE_CODE_INVALID_ALPN",
		6: "RESPONSE_CODE_REJECTED",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNKNOWN":          0,
		"RESPONSE_CODE_ACCEPTED":         1,
		"RESPONSE_CODE_INVALID_EXPIRES":  2,
		"RESPONSE_CODE_INVALID_IDENTITY": 3,
		"RESPONSE_CODE_INVALID_NAME":     4,
		"RESPONSE_CODE_INVALID_ALPN":     5,
		"RESPONSE_CODE_REJECTED":         6,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_portal_core_proto_rdverb_rdverb_proto_enumTypes[1].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_portal_core_proto_rdverb_rdverb_proto_enumTypes[1]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{1}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PacketType             `protobuf:"varint,1,opt,name=type,proto3,enum=rdverb.PacketType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_TYPE_RELAY_INFO_REQUEST
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RelayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *rdsec.Identity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Address       []string               `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Leases        []*Lease               `protobuf:"bytes,3,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayInfo) Reset() {
	*x = RelayInfo{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayInfo) ProtoMessage() {}

func (x *RelayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayInfo.ProtoReflect.Descriptor instead.
func (*RelayInfo) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{1}
}

func (x *RelayInfo) GetIdentity() *rdsec.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RelayInfo) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RelayInfo) GetLeases() []*Lease {
	if x != nil {
		return x.Leases
	}
	return nil
}

type RelayInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayInfoRequest) Reset() {
	*x = RelayInfoRequest{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayInfoRequest) ProtoMessage() {}

func (x *RelayInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayInfoRequest.ProtoReflect.Descriptor instead.
func (*RelayInfoRequest) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{2}
}

type RelayInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayInfo     *RelayInfo             `protobuf:"bytes,1,opt,name=relay_info,json=relayInfo,proto3" json:"relay_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayInfoResponse) Reset() {
	*x = RelayInfoResponse{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayInfoResponse) ProtoMessage() {}

func (x *RelayInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayInfoResponse.ProtoReflect.Descriptor instead.
func (*RelayInfoResponse) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{3}
}

func (x *RelayInfoResponse) GetRelayInfo() *RelayInfo {
	if x != nil {
		return x.RelayInfo
	}
	return nil
}

type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *rdsec.Identity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Expires       int64                  `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Alpn          []string               `protobuf:"bytes,4,rep,name=alpn,proto3" json:"alpn,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{4}
}

func (x *Lease) GetIdentity() *rdsec.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Lease) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Lease) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lease) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *Lease) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type LeaseUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseUpdateRequest) Reset() {
	*x = LeaseUpdateRequest{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseUpdateRequest) ProtoMessage() {}

func (x *LeaseUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseUpdateRequest.ProtoReflect.Descriptor instead.
func (*LeaseUpdateRequest) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{5}
}

func (x *LeaseUpdateRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *LeaseUpdateRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *LeaseUpdateRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LeaseUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=rdverb.ResponseCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseUpdateResponse) Reset() {
	*x = LeaseUpdateResponse{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseUpdateResponse) ProtoMessage() {}

func (x *LeaseUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseUpdateResponse.ProtoReflect.Descriptor instead.
func (*LeaseUpdateResponse) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{6}
}

func (x *LeaseUpdateResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNKNOWN
}

type LeaseDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *rdsec.Identity        `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseDeleteRequest) Reset() {
	*x = LeaseDeleteRequest{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseDeleteRequest) ProtoMessage() {}

func (x *LeaseDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseDeleteRequest.ProtoReflect.Descriptor instead.
func (*LeaseDeleteRequest) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseDeleteRequest) GetIdentity() *rdsec.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *LeaseDeleteRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *LeaseDeleteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LeaseDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=rdverb.ResponseCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseDeleteResponse) Reset() {
	*x = LeaseDeleteResponse{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseDeleteResponse) ProtoMessage() {}

func (x *LeaseDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseDeleteResponse.ProtoReflect.Descriptor instead.
func (*LeaseDeleteResponse) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseDeleteResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNKNOWN
}

type ConnectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LeaseId        string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ClientIdentity *rdsec.Identity        `protobuf:"bytes,2,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectionRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ConnectionRequest) GetClientIdentity() *rdsec.Identity {
	if x != nil {
		return x.ClientIdentity
	}
	return nil
}

type ConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=rdverb.ResponseCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portal_core_proto_rdverb_rdverb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNKNOWN
}

var File_portal_core_proto_rdverb_rdverb_proto protoreflect.FileDescriptor

const file_portal_core_proto_rdverb_rdverb_proto_rawDesc = "" +
	"\n" +
	"%portal/core/proto/rdverb/rdverb.proto\x12\x06rdverb\x1a#portal/core/proto/rdsec/rdsec.proto\"J\n" +
	"\x06Packet\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.rdverb.PacketTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"y\n" +
	"\tRelayInfo\x12+\n" +
	"\bidentity\x18\x01 \x01(\v2\x0f.rdsec.IdentityR\bidentity\x12\x18\n" +
	"\aaddress\x18\x02 \x03(\tR\aaddress\x12%\n" +
	"\x06leases\x18\x03 \x03(\v2\r.rdverb.LeaseR\x06leases\"\x12\n" +
	"\x10RelayInfoRequest\"E\n" +
	"\x11RelayInfoResponse\x120\n" +
	"\n" +
	"relay_info\x18\x01 \x01(\v2\x11.rdverb.RelayInfoR\trelayInfo\"\x92\x01\n" +
	"\x05Lease\x12+\n" +
	"\bidentity\x18\x01 \x01(\v2\x0f.rdsec.IdentityR\bidentity\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\x03R\aexpires\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04alpn\x18\x04 \x03(\tR\x04alpn\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"m\n" +
	"\x12LeaseUpdateRequest\x12#\n" +
	"\x05lease\x18\x01 \x01(\v2\r.rdverb.LeaseR\x05lease\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"?\n" +
	"\x13LeaseUpdateResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.rdverb.ResponseCodeR\x04code\"u\n" +
	"\x12LeaseDeleteRequest\x12+\n" +
	"\bidentity\x18\x01 \x01(\v2\x0f.rdsec.IdentityR\bidentity\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"?\n" +
	"\x13LeaseDeleteResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.rdverb.ResponseCodeR\x04code\"h\n" +
	"\x11ConnectionRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x128\n" +
	"\x0fclient_identity\x18\x02 \x01(\v2\x0f.rdsec.IdentityR\x0eclientIdentity\">\n" +
	"\x12ConnectionResponse\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.rdverb.ResponseCodeR\x04code*\xb8\x02\n" +
	"\n" +
	"PacketType\x12\"\n" +
	"\x1ePACKET_TYPE_RELAY_INFO_REQUEST\x10\x00\x12#\n" +
	"\x1fPACKET_TYPE_RELAY_INFO_RESPONSE\x10\x01\x12$\n" +
	" PACKET_TYPE_LEASE_UPDATE_REQUEST\x10\x02\x12%\n" +
	"!PACKET_TYPE_LEASE_UPDATE_RESPONSE\x10\x03\x12$\n" +
	" PACKET_TYPE_LEASE_DELETE_REQUEST\x10\x04\x12%\n" +
	"!PACKET_TYPE_LEASE_DELETE_RESPONSE\x10\x05\x12\"\n" +
	"\x1ePACKET_TYPE_CONNECTION_REQUEST\x10\x06\x12#\n" +
	"\x1fPACKET_TYPE_CONNECTION_RESPONSE\x10\a*\xe8\x01\n" +
	"\fResponseCode\x12\x19\n" +
	"\x15RESPONSE_CODE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16RESPONSE_CODE_ACCEPTED\x10\x01\x12!\n" +
	"\x1dRESPONSE_CODE_INVALID_EXPIRES\x10\x02\x12\"\n" +
	"\x1eRESPONSE_CODE_INVALID_IDENTITY\x10\x03\x12\x1e\n" +
	"\x1aRESPONSE_CODE_INVALID_NAME\x10\x04\x12\x1e\n" +
	"\x1aRESPONSE_CODE_INVALID_ALPN\x10\x05\x12\x1a\n" +
	"\x16RESPONSE_CODE_REJECTED\x10\x06B3Z1gosuda.org/portal/portal/core/proto/rdverb;rdverbb\x06proto3"

var (
	file_portal_core_proto_rdverb_rdverb_proto_rawDescOnce sync.Once
	file_portal_core_proto_rdverb_rdverb_proto_rawDescData []byte
)

func file_portal_core_proto_rdverb_rdverb_proto_rawDescGZIP() []byte {
	file_portal_core_proto_rdverb_rdverb_proto_rawDescOnce.Do(func() {
		file_portal_core_proto_rdverb_rdverb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portal_core_proto_rdverb_rdverb_proto_rawDesc), len(file_portal_core_proto_rdverb_rdverb_proto_rawDesc)))
	})
	return file_portal_core_proto_rdverb_rdverb_proto_rawDescData
}

var file_portal_core_proto_rdverb_rdverb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_portal_core_proto_rdverb_rdverb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_portal_core_proto_rdverb_rdverb_proto_goTypes = []any{
	(PacketType)(0),             // 0: rdverb.PacketType
	(ResponseCode)(0),           // 1: rdverb.ResponseCode
	(*Packet)(nil),              // 2: rdverb.Packet
	(*RelayInfo)(nil),           // 3: rdverb.RelayInfo
	(*RelayInfoRequest)(nil),    // 4: rdverb.RelayInfoRequest
	(*RelayInfoResponse)(nil),   // 5: rdverb.RelayInfoResponse
	(*Lease)(nil),               // 6: rdverb.Lease
	(*LeaseUpdateRequest)(nil),  // 7: rdverb.LeaseUpdateRequest
	(*LeaseUpdateResponse)(nil), // 8: rdverb.LeaseUpdateResponse
	(*LeaseDeleteRequest)(nil),  // 9: rdverb.LeaseDeleteRequest
	(*LeaseDeleteResponse)(nil), // 10: rdverb.LeaseDeleteResponse
	(*ConnectionRequest)(nil),   // 11: rdverb.ConnectionRequest
	(*ConnectionResponse)(nil),  // 12: rdverb.ConnectionResponse
	(*rdsec.Identity)(nil),      // 13: rdsec.Identity
}
var file_portal_core_proto_rdverb_rdverb_proto_depIdxs = []int32{
	0,  // 0: rdverb.Packet.type:type_name -> rdverb.PacketType
	13, // 1: rdverb.RelayInfo.identity:type_name -> rdsec.Identity
	6,  // 2: rdverb.RelayInfo.leases:type_name -> rdverb.Lease
	3,  // 3: rdverb.RelayInfoResponse.relay_info:type_name -> rdverb.RelayInfo
	13, // 4: rdverb.Lease.identity:type_name -> rdsec.Identity
	6,  // 5: rdverb.LeaseUpdateRequest.lease:type_name -> rdverb.Lease
	1,  // 6: rdverb.LeaseUpdateResponse.code:type_name -> rdverb.ResponseCode
	13, // 7: rdverb.LeaseDeleteRequest.identity:type_name -> rdsec.Identity
	1,  // 8: rdverb.LeaseDeleteResponse.code:type_name -> rdverb.ResponseCode
	13, // 9: rdverb.ConnectionRequest.client_identity:type_name -> rdsec.Identity
	1,  // 10: rdverb.ConnectionResponse.code:type_name -> rdverb.ResponseCode
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_portal_core_proto_rdverb_rdverb_proto_init() }
func file_portal_core_proto_rdverb_rdverb_proto_init() {
	if File_portal_core_proto_rdverb_rdverb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portal_core_proto_rdverb_rdverb_proto_rawDesc), len(file_portal_core_proto_rdverb_rdverb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_portal_core_proto_rdverb_rdverb_proto_goTypes,
		DependencyIndexes: file_portal_core_proto_rdverb_rdverb_proto_depIdxs,
		EnumInfos:         file_portal_core_proto_rdverb_rdverb_proto_enumTypes,
		MessageInfos:      file_portal_core_proto_rdverb_rdverb_proto_msgTypes,
	}.Build()
	File_portal_core_proto_rdverb_rdverb_proto = out.File
	file_portal_core_proto_rdverb_rdverb_proto_goTypes = nil
	file_portal_core_proto_rdverb_rdverb_proto_depIdxs = nil
}
