// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: portal/core/proto/rdverb/rdverb.proto
// Reflection-free version for TinyGo compatibility

package rdverb

import (
	rdsec "gosuda.org/portal/portal/core/proto/rdsec"
)

type PacketType int32

const (
	PacketType_PACKET_TYPE_RELAY_INFO_REQUEST    PacketType = 0
	PacketType_PACKET_TYPE_RELAY_INFO_RESPONSE   PacketType = 1
	PacketType_PACKET_TYPE_LEASE_UPDATE_REQUEST  PacketType = 2
	PacketType_PACKET_TYPE_LEASE_UPDATE_RESPONSE PacketType = 3
	PacketType_PACKET_TYPE_LEASE_DELETE_REQUEST  PacketType = 4
	PacketType_PACKET_TYPE_LEASE_DELETE_RESPONSE PacketType = 5
	PacketType_PACKET_TYPE_CONNECTION_REQUEST    PacketType = 6
	PacketType_PACKET_TYPE_CONNECTION_RESPONSE   PacketType = 7
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "PACKET_TYPE_RELAY_INFO_REQUEST",
		1: "PACKET_TYPE_RELAY_INFO_RESPONSE",
		2: "PACKET_TYPE_LEASE_UPDATE_REQUEST",
		3: "PACKET_TYPE_LEASE_UPDATE_RESPONSE",
		4: "PACKET_TYPE_LEASE_DELETE_REQUEST",
		5: "PACKET_TYPE_LEASE_DELETE_RESPONSE",
		6: "PACKET_TYPE_CONNECTION_REQUEST",
		7: "PACKET_TYPE_CONNECTION_RESPONSE",
	}
	PacketType_value = map[string]int32{
		"PACKET_TYPE_RELAY_INFO_REQUEST":    0,
		"PACKET_TYPE_RELAY_INFO_RESPONSE":   1,
		"PACKET_TYPE_LEASE_UPDATE_REQUEST":  2,
		"PACKET_TYPE_LEASE_UPDATE_RESPONSE": 3,
		"PACKET_TYPE_LEASE_DELETE_REQUEST":  4,
		"PACKET_TYPE_LEASE_DELETE_RESPONSE": 5,
		"PACKET_TYPE_CONNECTION_REQUEST":    6,
		"PACKET_TYPE_CONNECTION_RESPONSE":   7,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	s, ok := PacketType_name[int32(x)]
	if !ok {
		return "PacketType(" + string(rune('0'+x)) + ")"
	}
	return s
}

type ResponseCode int32

const (
	ResponseCode_RESPONSE_CODE_UNKNOWN          ResponseCode = 0
	ResponseCode_RESPONSE_CODE_ACCEPTED         ResponseCode = 1
	ResponseCode_RESPONSE_CODE_INVALID_EXPIRES  ResponseCode = 2
	ResponseCode_RESPONSE_CODE_INVALID_IDENTITY ResponseCode = 3
	ResponseCode_RESPONSE_CODE_INVALID_NAME     ResponseCode = 4
	ResponseCode_RESPONSE_CODE_INVALID_ALPN     ResponseCode = 5
	ResponseCode_RESPONSE_CODE_REJECTED         ResponseCode = 6
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "RESPONSE_CODE_UNKNOWN",
		1: "RESPONSE_CODE_ACCEPTED",
		2: "RESPONSE_CODE_INVALID_EXPIRES",
		3: "RESPONSE_CODE_INVALID_IDENTITY",
		4: "RESPONSE_CODE_INVALID_NAME",
		5: "RESPONSE_CODE_INVALID_ALPN",
		6: "RESPONSE_CODE_REJECTED",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNKNOWN":          0,
		"RESPONSE_CODE_ACCEPTED":         1,
		"RESPONSE_CODE_INVALID_EXPIRES":  2,
		"RESPONSE_CODE_INVALID_IDENTITY": 3,
		"RESPONSE_CODE_INVALID_NAME":     4,
		"RESPONSE_CODE_INVALID_ALPN":     5,
		"RESPONSE_CODE_REJECTED":         6,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	s, ok := ResponseCode_name[int32(x)]
	if !ok {
		return "ResponseCode(" + string(rune('0'+x)) + ")"
	}
	return s
}

type Packet struct {
	Type          PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=rdverb.PacketType" json:"type,omitempty"`
	Payload       []byte     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields []byte
}

func (x *Packet) Reset() {
	*x = Packet{}
}

func (x *Packet) ProtoMessage() {} // Stub for vtproto compatibility

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_TYPE_RELAY_INFO_REQUEST
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RelayInfo struct {
	Identity      *rdsec.Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Address       []string        `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Leases        []*Lease        `protobuf:"bytes,3,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields []byte
}

func (x *RelayInfo) Reset() {
	*x = RelayInfo{}
}

func (x *RelayInfo) ProtoMessage() {} // Stub for vtproto compatibility

func (x *RelayInfo) GetIdentity() *rdsec.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RelayInfo) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RelayInfo) GetLeases() []*Lease {
	if x != nil {
		return x.Leases
	}
	return nil
}

type RelayInfoRequest struct {
	unknownFields []byte
}

func (x *RelayInfoRequest) Reset() {
	*x = RelayInfoRequest{}
}

func (x *RelayInfoRequest) ProtoMessage() {} // Stub for vtproto compatibility

type RelayInfoResponse struct {
	RelayInfo     *RelayInfo `protobuf:"bytes,1,opt,name=relay_info,json=relayInfo,proto3" json:"relay_info,omitempty"`
	unknownFields []byte
}

func (x *RelayInfoResponse) Reset() {
	*x = RelayInfoResponse{}
}

func (x *RelayInfoResponse) ProtoMessage() {} // Stub for vtproto compatibility

func (x *RelayInfoResponse) GetRelayInfo() *RelayInfo {
	if x != nil {
		return x.RelayInfo
	}
	return nil
}

type Lease struct {
	Identity      *rdsec.Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Expires       int64           `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	Name          string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Alpn          []string        `protobuf:"bytes,4,rep,name=alpn,proto3" json:"alpn,omitempty"`
	Metadata      string          `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields []byte
}

func (x *Lease) Reset() {
	*x = Lease{}
}

func (x *Lease) ProtoMessage() {} // Stub for vtproto compatibility

func (x *Lease) GetIdentity() *rdsec.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Lease) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Lease) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lease) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *Lease) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type LeaseUpdateRequest struct {
	Lease         *Lease `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	Nonce         []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields []byte
}

func (x *LeaseUpdateRequest) Reset() {
	*x = LeaseUpdateRequest{}
}

func (x *LeaseUpdateRequest) ProtoMessage() {} // Stub for vtproto compatibility

func (x *LeaseUpdateRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *LeaseUpdateRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *LeaseUpdateRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LeaseUpdateResponse struct {
	Code          ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=rdverb.ResponseCode" json:"code,omitempty"`
	unknownFields []byte
}

func (x *LeaseUpdateResponse) Reset() {
	*x = LeaseUpdateResponse{}
}

func (x *LeaseUpdateResponse) ProtoMessage() {} // Stub for vtproto compatibility

func (x *LeaseUpdateResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNKNOWN
}

type LeaseDeleteRequest struct {
	Identity      *rdsec.Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Nonce         []byte          `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     int64           `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields []byte
}

func (x *LeaseDeleteRequest) Reset() {
	*x = LeaseDeleteRequest{}
}

func (x *LeaseDeleteRequest) ProtoMessage() {} // Stub for vtproto compatibility

func (x *LeaseDeleteRequest) GetIdentity() *rdsec.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *LeaseDeleteRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *LeaseDeleteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LeaseDeleteResponse struct {
	Code          ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=rdverb.ResponseCode" json:"code,omitempty"`
	unknownFields []byte
}

func (x *LeaseDeleteResponse) Reset() {
	*x = LeaseDeleteResponse{}
}

func (x *LeaseDeleteResponse) ProtoMessage() {} // Stub for vtproto compatibility

func (x *LeaseDeleteResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNKNOWN
}

type ConnectionRequest struct {
	LeaseId        string          `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ClientIdentity *rdsec.Identity `protobuf:"bytes,2,opt,name=client_identity,json=clientIdentity,proto3" json:"client_identity,omitempty"`
	unknownFields  []byte
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
}

func (x *ConnectionRequest) ProtoMessage() {} // Stub for vtproto compatibility

func (x *ConnectionRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ConnectionRequest) GetClientIdentity() *rdsec.Identity {
	if x != nil {
		return x.ClientIdentity
	}
	return nil
}

type ConnectionResponse struct {
	Code          ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=rdverb.ResponseCode" json:"code,omitempty"`
	unknownFields []byte
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
}

func (x *ConnectionResponse) ProtoMessage() {} // Stub for vtproto compatibility

func (x *ConnectionResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_RESPONSE_CODE_UNKNOWN
}
