version: "2"

run:
  tests: true
  # Go 1.25+ will handle modules impeccably; ensure the linter knows the version.
  go: "1.25"

linters:
  default: standard

  enable:
    # --- The Essentials (Bugs & Correctness) ---
    - govet # Standard vet
    - errcheck # Unchecked errors are fatal
    - staticcheck # Dominant static analysis
    - gochecknoglobals # Disallows global variables (improves concurrency safety)
    - gochecknoinits # Disallows init functions (can have concurrency implications)
    - gocritic # General linter with many checks, including some concurrency-related ones like deferInLoop
    - containedctx # Ensures context.Context is the first argument (improves context propagation)

    # --- The Dark Arts (Performance & Concurrency) ---
    - prealloc # Encourages slice pre-allocation (critical for low latency)
    - bodyclose # Ensures HTTP response bodies are closed
    - noctx # HTTP requests must have context (prevents goroutine leaks)
    - copyloopvar # Detects loop variable copying (Modern Go replacement for exportloopref)
    - intrange # Suggests using newer `for i := range n` syntax (Go 1.22+)

  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"

  settings:
    errcheck:
      # FALSE: Allows you to explicitly ignore an error using `_ = func()`
      # If true, `_ = func()` is still a violation.
      check-blank: false

      # FALSE: Does not force checking type assertion results (v, ok := x.(T))
      check-type-assertions: false

      # List of functions to exclude from checking.
      # These are the most common sources of "noise" in standard Go development.
      exclude-functions:
        - fmt.Printf
        - fmt.Println
        - fmt.Print
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Sprintf # Rarely fails unless OOM
        - os.Unsetenv # Usually safe to ignore
        - encoding/json.Marshal # Safe ONLY if you trust the struct tags/types
        - encoding/json.Unmarshal # Safe ONLY if you trust the input data
        - encoding/json.NewEncoder # Encoder setup
        - encoding/json.NewDecoder # Decoder setup
        - strings.Builder.WriteString # Writes to memory; usually safe
        - strings.Builder.Write # Writes to memory; usually safe
        - bytes.Buffer.Write # Writes to memory; usually safe
        - bytes.Buffer.WriteString # Writes to memory; usually safe
        - io.Copy # Standard I/O operation
        - context.WithTimeout # Context creation
        - context.WithCancel # Context creation
        - log.Printf # Standard logging
        - log.Println # Standard logging
        - log.Print # Standard logging
        - time.Now # Time retrieval
        - time.Sleep # Time operations
        - sync.Mutex.Lock # Mutex operations
        - sync.Mutex.Unlock # Mutex operations
        - sync.RWMutex.RLock # RWMutex operations
        - sync.RWMutex.RUnlock # RWMutex operations
        - atomic.AddInt64 # Atomic operations
        - atomic.StoreInt64 # Atomic operations
        - atomic.LoadInt64 # Atomic operations
        - rand.Read # Cryptographically secure random
        - crypto/rand.Read # Secure random source

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
