services:
  portal:
    image: ghcr.io/gosuda/portal:1
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "--adminport"
      - "${ADMIN_PORT:-4017}"
    environment:
      # Core configuration
      PORTAL_URL: ${PORTAL_URL:-http://localhost:${ADMIN_PORT:-4017}}
      BOOTSTRAP_URIS: ${BOOTSTRAP_URIS:-http://localhost:${ADMIN_PORT:-4017}}
      ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY:-}

      # TLS/SNI and keyless configurationa
      SNI_PORT: ${SNI_PORT:-443}
      KEYLESS_KEY_FILE: ${KEYLESS_KEY_FILE:-/etc/portal/keyless/privkey.pem}
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN:-}
    ports:
      - "${ADMIN_PORT:-4017}:${ADMIN_PORT:-4017}"
      - "80:80"
      - "443:443"
    volumes:
      - ./data/keyless:/etc/portal/keyless
    restart: unless-stopped
