package types

const (
	APIErrorCodeAuthDisabled        = "auth_disabled"
	APIErrorCodeFeatureUnavailable  = "feature_unavailable"
	APIErrorCodeHijackFailed        = "hijack_failed"
	APIErrorCodeHijackUnsupported   = "hijack_unsupported"
	APIErrorCodeHostnameConflict    = "hostname_conflict"
	APIErrorCodeHTTP11Only          = "http11_only"
	APIErrorCodeInvalidIP           = "invalid_ip"
	APIErrorCodeInvalidJSON         = "invalid_json"
	APIErrorCodeInvalidKey          = "invalid_key"
	APIErrorCodeInvalidLeaseID      = "invalid_lease_id"
	APIErrorCodeInvalidMode         = "invalid_mode"
	APIErrorCodeInvalidRequest      = "invalid_request"
	APIErrorCodeInternal            = "internal"
	APIErrorCodeIPBanned            = "ip_banned"
	APIErrorCodeLeaseNotFound       = "lease_not_found"
	APIErrorCodeLeaseRejected       = "lease_rejected"
	APIErrorCodeMethodNotAllowed    = "method_not_allowed"
	APIErrorCodeSessionCreateFailed = "session_create_failed"
	APIErrorCodeUnauthorized        = "unauthorized"
	APIErrorCodeUDPPortExhausted    = "udp_port_exhausted"
	APIErrorCodeUDPDisabled         = "udp_disabled"
	APIErrorCodeUDPCapacityExceeded = "udp_capacity_exceeded"
	APIErrorCodeTransportMismatch   = "transport_mismatch"

	MITMProbeReasonExporterMismatch = "tls_exporter_mismatch"
	MITMProbeReasonProbeTimeout     = "probe_timeout"
)
