package types

const (
	PathV1Sign            = "/v1/sign"
	PathHealthz           = "/healthz"
	PathRoot              = "/"
	PathAssetsPrefix      = "/assets/"
	PathApp               = "/app"
	PathAppPrefix         = "/app/"
	PathAdmin             = "/admin"
	PathAdminPrefix       = "/admin/"
	PathAdminSnapshot     = "/admin/snapshot"
	PathAdminLeases       = "/admin/leases"
	PathAdminLeasesPrefix = "/admin/leases/"
	PathAdminLogin        = "/admin/login"
	PathAdminLogout       = "/admin/logout"
	PathAdminAuthStatus   = "/admin/auth/status"
	PathAdminApproval     = "/admin/settings/approval-mode"
	PathAdminUDP          = "/admin/settings/udp"
	PathAdminIPsPrefix    = "/admin/ips/"
	PathInstallShell      = "/install.sh"
	PathInstallPowerShell = "/install.ps1"
	PathInstallBinPrefix  = "/install/bin/"

	PathSDKPrefix     = "/sdk/"
	PathSDKDomain     = "/sdk/domain"
	PathSDKRegister   = "/sdk/register"
	PathSDKRenew      = "/sdk/renew"
	PathSDKUnregister = "/sdk/unregister"
	PathSDKConnect    = "/sdk/connect"
	PathDiscovery     = "/discovery"
)
