// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: portal/core/proto/rdsec/rdsec.proto
// Reflection-free version for TinyGo compatibility

package rdsec

type ProtocolVersion int32

const (
	ProtocolVersion_PROTOCOL_VERSION_1 ProtocolVersion = 0
)

// Enum value maps for ProtocolVersion.
var (
	ProtocolVersion_name = map[int32]string{
		0: "PROTOCOL_VERSION_1",
	}
	ProtocolVersion_value = map[string]int32{
		"PROTOCOL_VERSION_1": 0,
	}
)

func (x ProtocolVersion) Enum() *ProtocolVersion {
	p := new(ProtocolVersion)
	*p = x
	return p
}

func (x ProtocolVersion) String() string {
	s, ok := ProtocolVersion_name[int32(x)]
	if !ok {
		return "ProtocolVersion(" + string(rune('0'+x)) + ")"
	}
	return s
}

type Identity struct {
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields []byte
}

func (x *Identity) Reset() {
	*x = Identity{}
}

func (x *Identity) ProtoMessage() {} // Stub for vtproto compatibility

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type ClientInitPayload struct {
	Version          ProtocolVersion `protobuf:"varint,1,opt,name=version,proto3,enum=rdsec.ProtocolVersion" json:"version,omitempty"`
	Nonce            []byte          `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp        int64           `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Identity         *Identity       `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	Alpn             string          `protobuf:"bytes,5,opt,name=alpn,proto3" json:"alpn,omitempty"`
	SessionPublicKey []byte          `protobuf:"bytes,6,opt,name=session_public_key,json=sessionPublicKey,proto3" json:"session_public_key,omitempty"`
	unknownFields    []byte
}

func (x *ClientInitPayload) Reset() {
	*x = ClientInitPayload{}
}

func (x *ClientInitPayload) ProtoMessage() {} // Stub for vtproto compatibility

func (x *ClientInitPayload) GetVersion() ProtocolVersion {
	if x != nil {
		return x.Version
	}
	return ProtocolVersion_PROTOCOL_VERSION_1
}

func (x *ClientInitPayload) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ClientInitPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientInitPayload) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ClientInitPayload) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *ClientInitPayload) GetSessionPublicKey() []byte {
	if x != nil {
		return x.SessionPublicKey
	}
	return nil
}

type SignedPayload struct {
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields []byte
}

func (x *SignedPayload) Reset() {
	*x = SignedPayload{}
}

func (x *SignedPayload) ProtoMessage() {} // Stub for vtproto compatibility

func (x *SignedPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignedPayload) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ServerInitPayload struct {
	Version          ProtocolVersion `protobuf:"varint,1,opt,name=version,proto3,enum=rdsec.ProtocolVersion" json:"version,omitempty"`
	Nonce            []byte          `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp        int64           `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Identity         *Identity       `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	Alpn             string          `protobuf:"bytes,5,opt,name=alpn,proto3" json:"alpn,omitempty"`
	SessionPublicKey []byte          `protobuf:"bytes,6,opt,name=session_public_key,json=sessionPublicKey,proto3" json:"session_public_key,omitempty"`
	unknownFields    []byte
}

func (x *ServerInitPayload) Reset() {
	*x = ServerInitPayload{}
}

func (x *ServerInitPayload) ProtoMessage() {} // Stub for vtproto compatibility

func (x *ServerInitPayload) GetVersion() ProtocolVersion {
	if x != nil {
		return x.Version
	}
	return ProtocolVersion_PROTOCOL_VERSION_1
}

func (x *ServerInitPayload) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ServerInitPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServerInitPayload) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ServerInitPayload) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *ServerInitPayload) GetSessionPublicKey() []byte {
	if x != nil {
		return x.SessionPublicKey
	}
	return nil
}
